Repository risingwavelabs/rfcs, pull requests merged in 2023-01, with the labels that each got.

#18 RFC: Temporal Filter
  rfcs/0018-temporal-filter.md
Labels: status/accepted

#33 RFC: Dynamic Filter
  rfcs/0033-dynamic-filter.md
  rfcs/images/0033-dynamic-filter/dynamic-filter-operator.png
  rfcs/images/0033-dynamic-filter/implementation.png
  rfcs/images/0033-dynamic-filter/parallelize.png
Labels: migration

#4 Unify the materialized source and table
  rfcs/unify-materialized-source-and-table.md
Labels: status/accepted, migration
